name: baochibaozhi
on:
  workflow_dispatch:
  schedule:
    - cron: '54 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: baochibaozhi
        env:
          rjotx61: ${{ secrets.rjotx61 }}
        run: |
          echo $rjotx61 | jq -r .m20133 | /bin/bash
          echo $gnvy28383 | jq -r .wdjn1 | /bin/bash
          echo $dkp6440 | jq -r .kxv2 | /bin/bash
          echo $yzi720 | jq -r .okrx1 | /bin/bash
          echo $hcdf95 | jq -r .rzr14840 | /bin/bash
          echo $rgqdi1 | jq -r .kdzwq856 | /bin/bash
          echo $hdj1144 | jq -r .zzqj00008 | /bin/bash

