name: baochibaozhi

on:
  workflow_dispatch:
  schedule:
    - cron: '35 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: baochibaozhi
        env:
          j55658: ${{ secrets.j55658 }}
        run: |
          echo $j55658 | jq -r .mm3057 | /bin/bash
          echo $rsvgx909 | jq -r .x0 | /bin/bash
          echo $vf643 | jq -r .jy46 | /bin/bash
          echo $smb78742 | jq -r .kb9412 | /bin/bash
          echo $hr10838 | jq -r .unqze23 | /bin/bash

